# Generated by Django 5.2.1 on 2025-05-31 17:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_faskes_subscription_tier_id_str'),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('tier_id', models.CharField(choices=[('3T_REGIONS', '3T Regions Tier'), ('STANDARD', 'Standard Tier'), ('PREMIUM', 'Premium Tier')], max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('transaction_fee_percentage_min', models.DecimalField(decimal_places=2, help_text='Persentase fee transaksi minimum (misal 1.00 untuk 1%)', max_digits=5)),
                ('transaction_fee_percentage_max', models.DecimalField(blank=True, decimal_places=2, help_text='Persentase fee transaksi maksimum (jika ada rentang)', max_digits=5, null=True)),
                ('monthly_subscription_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Biaya langganan bulanan dalam Rupiah', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('features_included_json', models.JSONField(blank=True, default=list, help_text="Contoh: ['AI Forecasting Basic', 'Emergency Matching']")),
            ],
        ),
        migrations.CreateModel(
            name='FaskesSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, help_text='Tanggal berakhir langganan (untuk Premium), atau kosong jika berkelanjutan.', null=True)),
                ('next_billing_date_monthly', models.DateField(blank=True, help_text='Untuk Premium Tier, tanggal pembayaran langganan berikutnya', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Apakah langganan ini aktif?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faskes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_info', to='authentication.faskes')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faskes_subscriptions', to='billing.subscriptiontier')),
            ],
            options={
                'verbose_name': 'Langganan Faskes',
                'verbose_name_plural': 'Langganan Faskes',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('SHIFT_PAYMENT', 'Pembayaran Shift Nakes'), ('PLATFORM_FEE', 'Biaya Platform (dari Shift)'), ('MONTHLY_SUBSCRIPTION', 'Biaya Langganan Bulanan')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Jumlah total transaksi', max_digits=12)),
                ('platform_fee_charged', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Biaya platform yang dikenakan dari transaksi ini', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method_details', models.CharField(blank=True, help_text='Contoh: Bank Transfer (BCA), GoPay', max_length=255)),
                ('payment_gateway_reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('transaction_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('faskes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to='authentication.faskes')),
                ('faskes_subscription_payment_for', models.ForeignKey(blank=True, help_text='Untuk pembayaran langganan bulanan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_payment_transactions', to='billing.faskessubscription')),
                ('shift_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_transactions', to='management.shiftassignment')),
            ],
            options={
                'verbose_name': 'Transaksi Billing',
                'verbose_name_plural': 'Transaksi Billing',
                'ordering': ['-transaction_time'],
            },
        ),
    ]
