# Generated by Django 5.2.1 on 2025-05-31 16:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nakes',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('profesi', models.CharField(choices=[('Perawat', 'Perawat'), ('Dokter Umum', 'Dokter Umum'), ('Bidan', 'Bidan'), ('Analis Laboratorium', 'Analis Laboratorium'), ('Dokter Gigi', 'Dokter Gigi'), ('Spesialis Anak', 'Spesialis Anak'), ('Spesialis Penyakit Dalam', 'Spesialis Penyakit Dalam'), ('Spesialis Bedah', 'Spesialis Bedah'), ('Spesialis Kandungan', 'Spesialis Kandungan'), ('Spesialis Mata', 'Spesialis Mata'), ('Spesialis THT', 'Spesialis THT'), ('Spesialis Jantung', 'Spesialis Jantung'), ('Spesialis Saraf', 'Spesialis Saraf'), ('Spesialis Kulit & Kelamin', 'Spesialis Kulit & Kelamin'), ('Spesialis Anastesi', 'Spesialis Anastesi'), ('Fisioterapis', 'Fisioterapis'), ('Apoteker', 'Apoteker'), ('Volunteer', 'Volunteer')], max_length=50)),
                ('status', models.CharField(choices=[('Unavaiable', 'Unavaiable'), ('Menerima Konsul', 'Menerima Konsul'), ('Avaiable', 'Avaiable')], max_length=50)),
                ('nomor_registrasi', models.CharField(help_text='Contoh: STR, SIP, dll.', max_length=100, unique=True)),
                ('tahun_pengalaman', models.IntegerField(default=0)),
                ('kategori_kualifikasi', models.CharField(choices=[('Perawat Umum', 'Perawat Umum'), ('Perawat Gigi', 'Perawat Gigi'), ('Perawat Anestesi', 'Perawat Anestesi'), ('Perawat Bedah', 'Perawat Bedah'), ('Dokter Umum', 'Dokter Umum'), ('Dokter Gigi', 'Dokter Gigi'), ('Bidan', 'Bidan'), ('Analis Kesehatan', 'Analis Kesehatan'), ('Pranata Laboratorium Kesehatan', 'Pranata Laboratorium Kesehatan'), ('Apoteker', 'Apoteker'), ('Fisioterapis', 'Fisioterapis'), ('Radiografer', 'Radiografer'), ('Nutrisionis', 'Nutrisionis'), ('Dietisien', 'Dietisien'), ('Perekam Medis', 'Perekam Medis'), ('Tenaga Kesehatan Lingkungan', 'Tenaga Kesehatan Lingkungan'), ('Tenaga Promosi Kesehatan', 'Tenaga Promosi Kesehatan'), ('Tenaga Teknis Biomedika', 'Tenaga Teknis Biomedika'), ('Asisten Tenaga Kesehatan', 'Asisten Tenaga Kesehatan'), ('Volunteer Medis', 'Volunteer Medis'), ('Spesialis Anak', 'Spesialis Anak'), ('Spesialis Penyakit Dalam', 'Spesialis Penyakit Dalam'), ('Spesialis Bedah Umum', 'Spesialis Bedah Umum'), ('Spesialis Bedah Ortopedi', 'Spesialis Bedah Ortopedi'), ('Spesialis Bedah Plastik', 'Spesialis Bedah Plastik'), ('Spesialis Bedah Saraf', 'Spesialis Bedah Saraf'), ('Spesialis Obstetri & Ginekologi', 'Spesialis Obstetri & Ginekologi'), ('Spesialis Mata', 'Spesialis Mata'), ('Spesialis THT', 'Spesialis THT'), ('Spesialis Jantung & Pembuluh Darah', 'Spesialis Jantung & Pembuluh Darah'), ('Spesialis Saraf', 'Spesialis Saraf'), ('Spesialis Kulit & Kelamin', 'Spesialis Kulit & Kelamin'), ('Spesialis Anestesiologi & Terapi Intensif', 'Spesialis Anestesiologi & Terapi Intensif'), ('Spesialis Paru', 'Spesialis Paru'), ('Spesialis Kedokteran Fisik & Rehabilitasi', 'Spesialis Kedokteran Fisik & Rehabilitasi'), ('Spesialis Patologi Klinik', 'Spesialis Patologi Klinik'), ('Spesialis Radiologi', 'Spesialis Radiologi'), ('Spesialis Forensik & Medikolegal', 'Spesialis Forensik & Medikolegal'), ('Spesialis Kesehatan Jiwa', 'Spesialis Kesehatan Jiwa'), ('Spesialis Gizi Klinik', 'Spesialis Gizi Klinik'), ('Spesialis Farmakologi Klinik', 'Spesialis Farmakologi Klinik'), ('Spesialis Gigi Anak', 'Spesialis Gigi Anak'), ('Spesialis Orthodonsia', 'Spesialis Orthodonsia'), ('Spesialis Konservasi Gigi', 'Spesialis Konservasi Gigi'), ('Spesialis Periodonsia', 'Spesialis Periodonsia'), ('Spesialis Penyakit Mulut', 'Spesialis Penyakit Mulut'), ('Spesialis Bedah Mulut', 'Spesialis Bedah Mulut'), ('Basic Life Support (BLS)', 'Basic Life Support (BLS)'), ('Advanced Cardiac Life Support (ACLS)', 'Advanced Cardiac Life Support (ACLS)'), ('Basic Trauma Life Support (BTLS)', 'Basic Trauma Life Support (BTLS)'), ('Advanced Trauma Life Support (ATLS)', 'Advanced Trauma Life Support (ATLS)'), ('Pelatihan Triase IGD', 'Pelatihan Triase IGD'), ('Sertifikasi Perawat ICU', 'Sertifikasi Perawat ICU'), ('Sertifikasi Perawat IGD', 'Sertifikasi Perawat IGD'), ('Sertifikasi Perawat Kamar Bedah', 'Sertifikasi Perawat Kamar Bedah'), ('Sertifikasi Perawat Hemodialisa', 'Sertifikasi Perawat Hemodialisa'), ('Sertifikasi Perawat Luka', 'Sertifikasi Perawat Luka'), ('Sertifikasi Phlebotomy', 'Sertifikasi Phlebotomy'), ('Sertifikasi EKG', 'Sertifikasi EKG'), ('Sertifikasi USG Dasar', 'Sertifikasi USG Dasar'), ('Pelatihan Resusitasi Neonatus', 'Pelatihan Resusitasi Neonatus'), ('Manajemen Nyeri', 'Manajemen Nyeri'), ('K3 Faskes', 'Kesehatan dan Keselamatan Kerja di Faskes'), ('Penanganan Bencana Medis', 'Penanganan Bencana Medis'), ('Pengendalian Infeksi (PPI)', 'Pengendalian Infeksi (PPI)'), ('Komunikasi Efektif', 'Komunikasi Efektif (untuk konseling pasien)'), ('Bahasa Inggris Medis', 'Keahlian Bahasa Inggris Medis'), ('Bahasa Mandarin Medis', 'Keahlian Bahasa Mandarin Medis'), ('Manajemen Faskes', 'Manajemen Faskes'), ('Quality Assurance Medis', 'Quality Assurance Medis'), ('Edukator Klinis', 'Edukator Klinis')], max_length=50)),
                ('log_ketersediaan_menit', models.IntegerField(default=0, help_text='Total menit yang diindikasikan Nakes bersedia bekerja. Perlu reset periodik.')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nakes',
                'verbose_name_plural': 'Nakes',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profesi', models.CharField(choices=[('Perawat', 'Perawat'), ('Dokter Umum', 'Dokter Umum'), ('Bidan', 'Bidan'), ('Analis Laboratorium', 'Analis Laboratorium'), ('Dokter Gigi', 'Dokter Gigi'), ('Spesialis Anak', 'Spesialis Anak'), ('Spesialis Penyakit Dalam', 'Spesialis Penyakit Dalam'), ('Spesialis Bedah', 'Spesialis Bedah'), ('Spesialis Kandungan', 'Spesialis Kandungan'), ('Spesialis Mata', 'Spesialis Mata'), ('Spesialis THT', 'Spesialis THT'), ('Spesialis Jantung', 'Spesialis Jantung'), ('Spesialis Saraf', 'Spesialis Saraf'), ('Spesialis Kulit & Kelamin', 'Spesialis Kulit & Kelamin'), ('Spesialis Anastesi', 'Spesialis Anastesi'), ('Fisioterapis', 'Fisioterapis'), ('Apoteker', 'Apoteker'), ('Volunteer', 'Volunteer')], max_length=50)),
                ('kategori_kualifikasi', models.CharField(choices=[('Perawat Umum', 'Perawat Umum'), ('Perawat Gigi', 'Perawat Gigi'), ('Perawat Anestesi', 'Perawat Anestesi'), ('Perawat Bedah', 'Perawat Bedah'), ('Dokter Umum', 'Dokter Umum'), ('Dokter Gigi', 'Dokter Gigi'), ('Bidan', 'Bidan'), ('Analis Kesehatan', 'Analis Kesehatan'), ('Pranata Laboratorium Kesehatan', 'Pranata Laboratorium Kesehatan'), ('Apoteker', 'Apoteker'), ('Fisioterapis', 'Fisioterapis'), ('Radiografer', 'Radiografer'), ('Nutrisionis', 'Nutrisionis'), ('Dietisien', 'Dietisien'), ('Perekam Medis', 'Perekam Medis'), ('Tenaga Kesehatan Lingkungan', 'Tenaga Kesehatan Lingkungan'), ('Tenaga Promosi Kesehatan', 'Tenaga Promosi Kesehatan'), ('Tenaga Teknis Biomedika', 'Tenaga Teknis Biomedika'), ('Asisten Tenaga Kesehatan', 'Asisten Tenaga Kesehatan'), ('Volunteer Medis', 'Volunteer Medis'), ('Spesialis Anak', 'Spesialis Anak'), ('Spesialis Penyakit Dalam', 'Spesialis Penyakit Dalam'), ('Spesialis Bedah Umum', 'Spesialis Bedah Umum'), ('Spesialis Bedah Ortopedi', 'Spesialis Bedah Ortopedi'), ('Spesialis Bedah Plastik', 'Spesialis Bedah Plastik'), ('Spesialis Bedah Saraf', 'Spesialis Bedah Saraf'), ('Spesialis Obstetri & Ginekologi', 'Spesialis Obstetri & Ginekologi'), ('Spesialis Mata', 'Spesialis Mata'), ('Spesialis THT', 'Spesialis THT'), ('Spesialis Jantung & Pembuluh Darah', 'Spesialis Jantung & Pembuluh Darah'), ('Spesialis Saraf', 'Spesialis Saraf'), ('Spesialis Kulit & Kelamin', 'Spesialis Kulit & Kelamin'), ('Spesialis Anestesiologi & Terapi Intensif', 'Spesialis Anestesiologi & Terapi Intensif'), ('Spesialis Paru', 'Spesialis Paru'), ('Spesialis Kedokteran Fisik & Rehabilitasi', 'Spesialis Kedokteran Fisik & Rehabilitasi'), ('Spesialis Patologi Klinik', 'Spesialis Patologi Klinik'), ('Spesialis Radiologi', 'Spesialis Radiologi'), ('Spesialis Forensik & Medikolegal', 'Spesialis Forensik & Medikolegal'), ('Spesialis Kesehatan Jiwa', 'Spesialis Kesehatan Jiwa'), ('Spesialis Gizi Klinik', 'Spesialis Gizi Klinik'), ('Spesialis Farmakologi Klinik', 'Spesialis Farmakologi Klinik'), ('Spesialis Gigi Anak', 'Spesialis Gigi Anak'), ('Spesialis Orthodonsia', 'Spesialis Orthodonsia'), ('Spesialis Konservasi Gigi', 'Spesialis Konservasi Gigi'), ('Spesialis Periodonsia', 'Spesialis Periodonsia'), ('Spesialis Penyakit Mulut', 'Spesialis Penyakit Mulut'), ('Spesialis Bedah Mulut', 'Spesialis Bedah Mulut'), ('Basic Life Support (BLS)', 'Basic Life Support (BLS)'), ('Advanced Cardiac Life Support (ACLS)', 'Advanced Cardiac Life Support (ACLS)'), ('Basic Trauma Life Support (BTLS)', 'Basic Trauma Life Support (BTLS)'), ('Advanced Trauma Life Support (ATLS)', 'Advanced Trauma Life Support (ATLS)'), ('Pelatihan Triase IGD', 'Pelatihan Triase IGD'), ('Sertifikasi Perawat ICU', 'Sertifikasi Perawat ICU'), ('Sertifikasi Perawat IGD', 'Sertifikasi Perawat IGD'), ('Sertifikasi Perawat Kamar Bedah', 'Sertifikasi Perawat Kamar Bedah'), ('Sertifikasi Perawat Hemodialisa', 'Sertifikasi Perawat Hemodialisa'), ('Sertifikasi Perawat Luka', 'Sertifikasi Perawat Luka'), ('Sertifikasi Phlebotomy', 'Sertifikasi Phlebotomy'), ('Sertifikasi EKG', 'Sertifikasi EKG'), ('Sertifikasi USG Dasar', 'Sertifikasi USG Dasar'), ('Pelatihan Resusitasi Neonatus', 'Pelatihan Resusitasi Neonatus'), ('Manajemen Nyeri', 'Manajemen Nyeri'), ('K3 Faskes', 'Kesehatan dan Keselamatan Kerja di Faskes'), ('Penanganan Bencana Medis', 'Penanganan Bencana Medis'), ('Pengendalian Infeksi (PPI)', 'Pengendalian Infeksi (PPI)'), ('Komunikasi Efektif', 'Komunikasi Efektif (untuk konseling pasien)'), ('Bahasa Inggris Medis', 'Keahlian Bahasa Inggris Medis'), ('Bahasa Mandarin Medis', 'Keahlian Bahasa Mandarin Medis'), ('Manajemen Faskes', 'Manajemen Faskes'), ('Quality Assurance Medis', 'Quality Assurance Medis'), ('Edukator Klinis', 'Edukator Klinis')], max_length=50)),
                ('jumlah_nakes_dibutuhkan', models.IntegerField(default=1)),
                ('tanggal_shift', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('durasi_menit', models.IntegerField(help_text='Durasi shift dalam menit')),
                ('deskripsi_tugas', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Apakah shift masih dibuka untuk penugasan')),
                ('is_completed_by_faskes', models.BooleanField(default=False, help_text='Apakah Faskes sudah menandai shift selesai')),
                ('departemen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='authentication.departemen')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_assignment', models.CharField(choices=[('Pending', 'Pending (Menunggu Nakes menerima)'), ('Accepted', 'Accepted (Diterima Nakes)'), ('Rejected', 'Rejected (Ditolak Nakes)'), ('Clocked In', 'Clocked In'), ('Clocked Out', 'Clocked Out'), ('Completed', 'Completed (Tugas Selesai oleh Nakes)'), ('Cancelled', 'Cancelled (Dibatalkan)')], default='Pending', max_length=50)),
                ('waktu_penugasan', models.DateTimeField(auto_now_add=True)),
                ('waktu_nakes_menerima', models.DateTimeField(blank=True, null=True)),
                ('waktu_clock_in', models.DateTimeField(blank=True, null=True)),
                ('waktu_clock_out', models.DateTimeField(blank=True, null=True)),
                ('total_bayaran_nakes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('nakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_shifts', to='management.nakes')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='management.shift')),
            ],
            options={
                'unique_together': {('shift', 'nakes')},
            },
        ),
        migrations.CreateModel(
            name='NakesSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(choices=[('Perawat Umum', 'Perawat Umum'), ('Perawat Gigi', 'Perawat Gigi'), ('Perawat Anestesi', 'Perawat Anestesi'), ('Perawat Bedah', 'Perawat Bedah'), ('Dokter Umum', 'Dokter Umum'), ('Dokter Gigi', 'Dokter Gigi'), ('Bidan', 'Bidan'), ('Analis Kesehatan', 'Analis Kesehatan'), ('Pranata Laboratorium Kesehatan', 'Pranata Laboratorium Kesehatan'), ('Apoteker', 'Apoteker'), ('Fisioterapis', 'Fisioterapis'), ('Radiografer', 'Radiografer'), ('Nutrisionis', 'Nutrisionis'), ('Dietisien', 'Dietisien'), ('Perekam Medis', 'Perekam Medis'), ('Tenaga Kesehatan Lingkungan', 'Tenaga Kesehatan Lingkungan'), ('Tenaga Promosi Kesehatan', 'Tenaga Promosi Kesehatan'), ('Tenaga Teknis Biomedika', 'Tenaga Teknis Biomedika'), ('Asisten Tenaga Kesehatan', 'Asisten Tenaga Kesehatan'), ('Volunteer Medis', 'Volunteer Medis'), ('Spesialis Anak', 'Spesialis Anak'), ('Spesialis Penyakit Dalam', 'Spesialis Penyakit Dalam'), ('Spesialis Bedah Umum', 'Spesialis Bedah Umum'), ('Spesialis Bedah Ortopedi', 'Spesialis Bedah Ortopedi'), ('Spesialis Bedah Plastik', 'Spesialis Bedah Plastik'), ('Spesialis Bedah Saraf', 'Spesialis Bedah Saraf'), ('Spesialis Obstetri & Ginekologi', 'Spesialis Obstetri & Ginekologi'), ('Spesialis Mata', 'Spesialis Mata'), ('Spesialis THT', 'Spesialis THT'), ('Spesialis Jantung & Pembuluh Darah', 'Spesialis Jantung & Pembuluh Darah'), ('Spesialis Saraf', 'Spesialis Saraf'), ('Spesialis Kulit & Kelamin', 'Spesialis Kulit & Kelamin'), ('Spesialis Anestesiologi & Terapi Intensif', 'Spesialis Anestesiologi & Terapi Intensif'), ('Spesialis Paru', 'Spesialis Paru'), ('Spesialis Kedokteran Fisik & Rehabilitasi', 'Spesialis Kedokteran Fisik & Rehabilitasi'), ('Spesialis Patologi Klinik', 'Spesialis Patologi Klinik'), ('Spesialis Radiologi', 'Spesialis Radiologi'), ('Spesialis Forensik & Medikolegal', 'Spesialis Forensik & Medikolegal'), ('Spesialis Kesehatan Jiwa', 'Spesialis Kesehatan Jiwa'), ('Spesialis Gizi Klinik', 'Spesialis Gizi Klinik'), ('Spesialis Farmakologi Klinik', 'Spesialis Farmakologi Klinik'), ('Spesialis Gigi Anak', 'Spesialis Gigi Anak'), ('Spesialis Orthodonsia', 'Spesialis Orthodonsia'), ('Spesialis Konservasi Gigi', 'Spesialis Konservasi Gigi'), ('Spesialis Periodonsia', 'Spesialis Periodonsia'), ('Spesialis Penyakit Mulut', 'Spesialis Penyakit Mulut'), ('Spesialis Bedah Mulut', 'Spesialis Bedah Mulut'), ('Basic Life Support (BLS)', 'Basic Life Support (BLS)'), ('Advanced Cardiac Life Support (ACLS)', 'Advanced Cardiac Life Support (ACLS)'), ('Basic Trauma Life Support (BTLS)', 'Basic Trauma Life Support (BTLS)'), ('Advanced Trauma Life Support (ATLS)', 'Advanced Trauma Life Support (ATLS)'), ('Pelatihan Triase IGD', 'Pelatihan Triase IGD'), ('Sertifikasi Perawat ICU', 'Sertifikasi Perawat ICU'), ('Sertifikasi Perawat IGD', 'Sertifikasi Perawat IGD'), ('Sertifikasi Perawat Kamar Bedah', 'Sertifikasi Perawat Kamar Bedah'), ('Sertifikasi Perawat Hemodialisa', 'Sertifikasi Perawat Hemodialisa'), ('Sertifikasi Perawat Luka', 'Sertifikasi Perawat Luka'), ('Sertifikasi Phlebotomy', 'Sertifikasi Phlebotomy'), ('Sertifikasi EKG', 'Sertifikasi EKG'), ('Sertifikasi USG Dasar', 'Sertifikasi USG Dasar'), ('Pelatihan Resusitasi Neonatus', 'Pelatihan Resusitasi Neonatus'), ('Manajemen Nyeri', 'Manajemen Nyeri'), ('K3 Faskes', 'Kesehatan dan Keselamatan Kerja di Faskes'), ('Penanganan Bencana Medis', 'Penanganan Bencana Medis'), ('Pengendalian Infeksi (PPI)', 'Pengendalian Infeksi (PPI)'), ('Komunikasi Efektif', 'Komunikasi Efektif (untuk konseling pasien)'), ('Bahasa Inggris Medis', 'Keahlian Bahasa Inggris Medis'), ('Bahasa Mandarin Medis', 'Keahlian Bahasa Mandarin Medis'), ('Manajemen Faskes', 'Manajemen Faskes'), ('Quality Assurance Medis', 'Quality Assurance Medis'), ('Edukator Klinis', 'Edukator Klinis')], max_length=100)),
                ('category', models.CharField(blank=True, choices=[('profesi_umum', 'Profesi Umum'), ('spesialisasi', 'Spesialisasi'), ('sertifikasi', 'Sertifikasi & Pelatihan'), ('manajemen', 'Manajemen & Administrasi')], max_length=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Apakah skill ini sudah diverifikasi')),
                ('nakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='management.nakes')),
            ],
            options={
                'verbose_name': 'Nakes Skill',
                'verbose_name_plural': 'Nakes Skills',
                'ordering': ['category', 'skill_name'],
                'unique_together': {('nakes', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='ReviewNakes',
            fields=[
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating_kinerja', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating kinerja Nakes (skala 1-5)')),
                ('komentar', models.TextField(blank=True, help_text='Komentar atau catatan mengenai kinerja Nakes', null=True)),
                ('tanggal_review', models.DateTimeField(auto_now_add=True)),
                ('faskes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to='authentication.faskes')),
                ('nakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='management.nakes')),
                ('assignment', models.OneToOneField(help_text='Review terkait dengan satu penugasan shift tertentu', on_delete=django.db.models.deletion.CASCADE, related_name='review_faskes', to='management.shiftassignment')),
            ],
            options={
                'unique_together': {('assignment', 'faskes')},
            },
        ),
    ]
