# Generated by Django 5.2.1 on 2025-05-31 12:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiForecastRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_reference_id', models.CharField(db_index=True, help_text='ID referensi dari sistem pemanggil (misal, Faskes ID)', max_length=255)),
                ('service_type', models.CharField(default='staffing_demand_forecast', max_length=100)),
                ('input_payload_json', models.JSONField(help_text='Payload JSON lengkap yang dikirimkan untuk AI')),
                ('raw_ai_response_text', models.TextField(blank=True, null=True)),
                ('parsed_ai_output_json', models.JSONField(blank=True, help_text='Output AI yang sudah diparsing ke JSON terstruktur', null=True)),
                ('ai_model_name_used', models.CharField(blank=True, max_length=100, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'AI Service Request Log',
                'verbose_name_plural': 'AI Service Request Logs',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RegionalRiskAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_reference_id', models.CharField(db_index=True, help_text='ID Region atau referensi geografis', max_length=255)),
                ('input_data_summary_text', models.TextField(help_text='Teks ringkasan data (misal dari BNPB) yang dianalisis AI')),
                ('risk_level_predicted', models.CharField(blank=True, max_length=50, null=True)),
                ('risk_justification_text', models.TextField(blank=True, null=True)),
                ('potential_hazards_json', models.JSONField(blank=True, null=True)),
                ('raw_ai_response_text', models.TextField(blank=True, null=True)),
                ('ai_model_name_used', models.CharField(blank=True, max_length=100, null=True)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AiModelPerformanceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_data_json', models.JSONField(help_text='Data aktual yang relevan dengan prediksi (misal, realisasi staf)')),
                ('accuracy_metrics_json', models.JSONField(blank=True, help_text='Skor akurasi detail yang dihitung', null=True)),
                ('overall_accuracy_score', models.FloatField(blank=True, null=True)),
                ('qualitative_feedback', models.TextField(blank=True, help_text='Feedback kualitatif dari pengguna atau sistem pemanggil', null=True)),
                ('feedback_provided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accuracy_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_request_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_feedback', to='ai_service.aiforecastrequestlog')),
            ],
            options={
                'verbose_name': 'AI Model Performance Feedback',
                'verbose_name_plural': 'AI Model Performance Feedbacks',
                'ordering': ['-feedback_provided_at'],
            },
        ),
    ]
