# Generated by Django 5.2.1 on 2025-05-31 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faskes',
            fields=[
                ('faskes_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_faskes', models.CharField(max_length=255)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tipe_faskes', models.CharField(blank=True, help_text='Contoh: Rumah Sakit, Puskesmas, Klinik', max_length=100, null=True)),
                ('nomor_telepon', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama_departemen', models.CharField(max_length=255)),
                ('jam_buka', models.TimeField(blank=True, null=True)),
                ('jam_tutup', models.TimeField(blank=True, null=True)),
                ('faskes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departemen', to='authentication.faskes')),
            ],
        ),
    ]
