# Generated by Django 5.2.1 on 2025-05-31 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faskes',
            fields=[
                ('faskes_id_internal', models.CharField(help_text='ID unik internal Faskes Partner', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nama_faskes', models.CharField(max_length=255)),
                ('jenis_faskes', models.CharField(max_length=100)),
                ('alamat_jalan', models.CharField(max_length=255)),
                ('alamat_kelurahan_desa', models.CharField(max_length=100)),
                ('alamat_kecamatan', models.CharField(max_length=100)),
                ('alamat_kota_kabupaten', models.CharField(max_length=100)),
                ('alamat_provinsi', models.CharField(max_length=100)),
                ('alamat_kode_pos', models.CharField(blank=True, max_length=10)),
                ('koordinat_latitude', models.FloatField(blank=True, null=True)),
                ('koordinat_longitude', models.FloatField(blank=True, null=True)),
                ('nomor_izin_operasional', models.CharField(blank=True, max_length=100)),
                ('pic_nama', models.CharField(blank=True, max_length=255)),
                ('pic_telepon', models.CharField(blank=True, max_length=20)),
                ('pic_email', models.EmailField(blank=True, max_length=254)),
                ('ops_hari', models.CharField(blank=True, max_length=100)),
                ('ops_jam_buka', models.TimeField(blank=True, null=True)),
                ('ops_jam_tutup', models.TimeField(blank=True, null=True)),
                ('ops_catatan', models.TextField(blank=True)),
                ('kapasitas_info_json', models.JSONField(blank=True, help_text='{"tempat_tidur": 100, "poli_aktif": 5}', null=True)),
                ('layanan_unggulan_json', models.JSONField(blank=True, help_text='["UGD", "Poli Anak"]', null=True)),
                ('historis_kunjungan_bulanan_json', models.JSONField(blank=True, null=True)),
                ('rata_kunjungan_harian_seminggu_json', models.JSONField(blank=True, null=True)),
                ('pola_kunjungan_layanan_json', models.JSONField(blank=True, null=True)),
                ('periode_puncak_diketahui_json', models.JSONField(blank=True, null=True)),
                ('historis_klb_lokal_json', models.JSONField(blank=True, null=True)),
                ('baseline_staffing_json', models.JSONField(blank=True, null=True)),
                ('is_active_partner', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama_departemen', models.CharField(max_length=255)),
                ('jam_buka', models.TimeField(blank=True, null=True)),
                ('jam_tutup', models.TimeField(blank=True, null=True)),
                ('faskes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departemen', to='authentication.faskes')),
            ],
        ),
    ]
