# Generated by Django 4.2.6 on 2025-05-31 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(help_text='Contoh: Gempa Bumi, Banjir, Wabah Penyakit', max_length=100)),
                ('location_description', models.CharField(help_text='Deskripsi singkat lokasi terdampak utama', max_length=255)),
                ('severity_level', models.IntegerField(choices=[(1, 'Level 1 (Siaga)'), (2, 'Level 2 (Waspada)'), (3, 'Level 3 (Awas/Darurat Tinggi)')], default=1)),
                ('affected_regions_input', models.TextField(help_text='Daftar wilayah terdampak (Kabupaten/Kota), pisahkan dengan koma. Misal: Kab. Cianjur, Kota Palu')),
                ('description', models.TextField(blank=True, help_text='Deskripsi tambahan mengenai situasi darurat', null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_time', models.DateTimeField(blank=True, null=True)),
                ('deactivation_time', models.DateTimeField(blank=True, null=True)),
                ('triggered_by_api', models.BooleanField(default=False, help_text='Apakah dipicu otomatis oleh API BNPB/BPBD?')),
                ('api_alert_details', models.JSONField(blank=True, help_text='Detail alert dari API jika ada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manually_triggered_by', models.ForeignKey(blank=True, help_text='Admin yang memicu secara manual', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_emergencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kejadian Darurat',
                'verbose_name_plural': 'Kejadian Darurat',
                'ordering': ['-activation_time'],
            },
        ),
    ]
