# Generated by Django 5.2.1 on 2025-05-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyevent',
            name='expanded_matching_radius_km',
            field=models.PositiveIntegerField(blank=True, help_text='Radius pencocokan yang diperluas dalam KM. Kosongkan jika menggunakan radius standar.', null=True),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='matching_acceleration_enabled',
            field=models.BooleanField(default=False, help_text='Apakah akselerasi pencocokan SDM diaktifkan untuk kejadian ini?'),
        ),
    ]
