# Generated by Django 5.2.1 on 2025-05-31 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergencyevent_expanded_matching_radius_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contoh: Logistik, Administrasi, Transportasi, Dapur Umum', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategori Tugas Relawan',
                'verbose_name_plural': 'Kategori Tugas Relawan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Email ini akan digunakan untuk komunikasi.', max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Nomor HP/WA aktif.', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Alamat domisili saat ini.', null=True)),
                ('id_number', models.CharField(blank=True, help_text='Nomor KTP/SIM/Identitas Lain (untuk verifikasi).', max_length=50, null=True)),
                ('emergency_contact_name', models.CharField(help_text='Nama kontak darurat.', max_length=100)),
                ('emergency_contact_phone', models.CharField(help_text='Nomor telepon kontak darurat.', max_length=20)),
                ('has_completed_basic_training', models.BooleanField(default=False, help_text='Konfirmasi telah membaca/menyelesaikan modul training dasar respons bencana (online 30 menit).')),
                ('skills_description', models.TextField(blank=True, help_text='Keahlian relevan (mis: menyetir, P3K dasar, memasak, entri data).', null=True)),
                ('is_profile_verified_by_admin', models.BooleanField(default=False, help_text='Apakah profil relawan sudah diverifikasi oleh admin?')),
                ('admin_verification_notes', models.TextField(blank=True, help_text='Catatan internal admin terkait verifikasi profil.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Relawan',
                'verbose_name_plural': 'Profil Relawan',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_notes', models.TextField(blank=True, help_text='Contoh: Tersedia penuh mulai besok, atau hanya akhir pekan, atau setiap hari setelah jam 5 sore.', null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Review'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('DEPLOYED', 'Sedang Bertugas'), ('COMPLETED', 'Selesai Bertugas'), ('CANCELLED', 'Dibatalkan oleh Relawan')], default='PENDING', max_length=20)),
                ('assigned_task_detail', models.TextField(blank=True, help_text='Detail tugas spesifik yang diberikan oleh admin.', null=True)),
                ('assigned_location_detail', models.CharField(blank=True, help_text='Detail lokasi penugasan spesifik (jika berbeda dari lokasi umum event).', max_length=255, null=True)),
                ('deployment_start_time', models.DateTimeField(blank=True, null=True)),
                ('deployment_end_time', models.DateTimeField(blank=True, null=True)),
                ('admin_application_notes', models.TextField(blank=True, help_text='Catatan dari admin terkait aplikasi/penugasan ini.', null=True)),
                ('emergency_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_applications', to='emergency.emergencyevent')),
                ('task_categories_preference', models.ManyToManyField(blank=True, help_text='Pilih satu atau lebih kategori tugas yang diminati.', to='emergency.taskcategory')),
                ('volunteer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='emergency.volunteerprofile')),
            ],
            options={
                'verbose_name': 'Aplikasi Relawan',
                'verbose_name_plural': 'Aplikasi Relawan',
                'ordering': ['-application_date'],
                'unique_together': {('emergency_event', 'volunteer_profile')},
            },
        ),
    ]
