# Generated by Django 5.2.1 on 2025-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_seed_initial_task_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyevent',
            name='ai_pre_positioning_recommendations_text',
            field=models.TextField(blank=True, help_text='Rekomendasi pre-positioning SDM atau sumber daya dari AI.', null=True),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='ai_regional_risk_assessment_results_json',
            field=models.JSONField(blank=True, help_text="Hasil penilaian risiko dari AI untuk wilayah terdampak. Format: [{'region': 'nama', 'level': 'Tinggi', ...}]", null=True),
        ),
    ]
